### ISSUE TITLE
Output VCF is not sorted by coordinate

### ISSUE THREAD

**Issue by nh13** [tfwillems/HipSTR#26]
Also, the VCF is missing contig lines in the header, which could easily be inferred from the a `.dict` or `.fai` file accompanying the FASTA, or if the input support an interval list rather than a BED file.

**Comment by tfwillems** [comment]
Previously, HipSTR VCFs were almost fully sorted, apart from some edge cases in which nearby STRs had their orders swapped in the output VCF. Due to commits 63714613a2f47f42803a32cde4599a0a38ab2932 and 56bc469b0b034888d255d03b7fb4953abe8534c3, HipSTR should now produce a VCF that is always properly sorted and also contains the contig fields in the header. If you have any input files that break this, I'd be eager to see them and fix it accordingly
