### ISSUE TITLE
Filter out reads that do not span an STR region

### ISSUE THREAD

**Issue by nh13** [tfwillems/HipSTR#33]
It looks like this command line option was [here previously](https://github.com/tfwillems/HipSTR/blob/92124b240da72404d320b69b8fd0566f108967a5/src/hipstr_main.cpp#L98), any objection to adding an option `--require-spanning-reads`?  In my application, we frequently get reads that start/end within a long STR and can cause false calls in a few samples.

**Comment by tfwillems** [comment]
I removed this option because in general, using all reads leads to improved accuracy relative to simply using reads that span the STR. Of course, there are cases in which only non-spanning reads are available and in these instances there will likely be genotyping errors. But in my opinion, it makes more sense to use all of the data and then use variant filtering to remove potentially erroneous genotypes. I would suggest looking at the MALLREADS FORMAT field (breaks down the spanning read support for each genotype) and the AB FORMAT field (allele bias, large negative values are bad) to detect cases in which these issues may be arising.

**Comment by tfwillems** [comment]
If you think something else might be at play in your instances, it'd be great if you could email me an example dataset so I can debug in more detail

**Comment by nh13** [comment]
@tfwillems happy to do so, do you have a preferred email?

**Comment by tfwillems** [comment]
Yep, my github username @ gmail

**Comment by tfwillems** [comment]
Hi @nh13 ,

It looks like applying quality-control filters to the genotypes solved your issue. Just requiring a posterior confidence greater than 90% (Q > 0.9) and 1 or more spanning reads (non-empty MALLREADS field) filtered out all of the noise. These filters can be applied using the [*filter_vcf.py*](https://github.com/tfwillems/HipSTR/blob/master/scripts/filter_vcf.py) or [*filter_haploid_vcf.py*](https://github.com/tfwillems/HipSTR/blob/master/scripts/filter_haploid_vcf.py) scripts included in the HipSTR distribution.

I've sent you an email summarizing the results

Best,
Thomas
