### ISSUE TITLE
All input reads filtered as "did not have a unique mapping"

### ISSUE THREAD

**Issue by npilshchikova** [tfwillems/HipSTR#41]
I'm trying to use HipSTR tool on Ion PGM data aligned by TMAP, but no reads for my target loci passed "did not have a unique mapping" filter (according to log file) in spite of high mapping quality (above 60) and absence of "secondary" or "supplementary" flags. What is the reason for this filtration? May be, this is non-standard flags in bam file issue?
I can send and example bam file, if it may be helpful (unfortunately, I don't see any way to add files to this issue).

P.S. I understand that Ion PGM sequencing data is not Illumina's, but it is interesting to test HipSTR on our data since lack of STR-calling tools developed for Ion Torrent.

**Comment by tfwillems** [comment]
While we definitely designed HipSTR for Illumina data, I'm more than happy to help you try it on Ion Torrent data.

I suspect this may be due to differences in the AS and XS tags reported by TMAP. For BWA-MEM, we use these to ensure that the XA tags were properly reported if a read has many possible alternative alignments. How long are the reads you're aligning?

Could you send an example BAM and region file to hipstrtool@gmail.com? I'm currently on vacation but will dig into it when I get back in mid-September. Data for a few loci where you're confident reads are valid should suffice.

Thanks!

Thomas

**Comment by tfwillems** [comment]
@npilshchikova, could you email me the files if you're still having this issue?
