### ISSUE TITLE
No GL output in Model 1

### ISSUE THREAD

**Issue by shukwong** [tfwillems/HipSTR#43]
Hi Thomas,

I ran HipSTR with Model 1 and then ran DenovoFinder. It complains that GL field is not found. Do I have to have extra parameters with Model 1 to have HipSTR output the GL field?

Thanks,
Wendy

**Comment by tfwillems** [comment]
Hi Wendy,

Yes, you need to specify **--output-gls** in order for a GL FORMAT field to be output to the VCF. By default, this is disabled as the GL's can cause the VCF file to become much larger due to the large number of alleles at many STR loci. However, if you're interested in using *DenovoFinder*, you'll need this field. You may also want to specify **--output-phased-gls** if 1) you are using phased SNP VCFs as input to **--snp-vcf** and 2) you have phased quads instead of trios

Best,
Thomas

**Comment by shukwong** [comment]
Thanks, Thomas!
I am rerunning them now and GL is being outputted. I have mostly trios and only a handful of quads (although I do have phaseByTransmission VCFs) so I won't be running --output-phased-gls.

Best,
Wendy
