### ISSUE TITLE
filter_haploid_vcf.py

### ISSUE THREAD

**Issue by JiruHan** [tfwillems/HipSTR#72]
Hello, I'd like to inquiry the problems that I meet, when I run filter_haploid_vcf.py, I have some error below:
Traceback (most recent call last):
  File "scripts/filter_haploid_vcf.py", line 281, in <module>
    main()
  File "scripts/filter_haploid_vcf.py", line 137, in main
    gt_a = int(sample['GT'])
ValueError: invalid literal for int() with base 10: '0|2'
Could you please take a look? Thanks in advance!

**Comment by tfwillems** [comment]
Hi @JiruHan,

Hopefully you managed to resolve your issue, but it's caused by the fact that your VCF contains diploid genotypes, not haploid genotypes. 

If you're genotyping a haploid chromosome, make sure you specify **--haploid-chrs** while running HipSTR and you can then use this script.

If you're genotyping a diploid chromosome, you'll want to use the [filter_vcf.py](https://github.com/tfwillems/HipSTR/blob/master/scripts/filter_vcf.py) script instead.

**Comment by JiruHan** [comment]
Hi there,

Many thanks for your reply!
I have solved the problem, before I use --hap-chr-file, now I add --haploid-chrs, and it’s working.
Thanks so much for your time!

Best wishes,
Jiru
